version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  service:
    restart: always
    build:
      dockerfile: Dockerfile
    container_name: effective_mobile_app
    depends_on:
      - postgres
    environment:
      PG_DSN: ${PG_DSN}
    ports:
      - "8080:8080"